import turtle
turtle.shape('turtle')
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(60, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(-20,80)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.width(3)
turtle.circle(10, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(20,80)
turtle.pendown()
turtle.begin_fill()
turtle.width(3)
turtle.circle(10, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(0,60)
turtle.pendown()
turtle.begin_fill()
turtle.width(7)
turtle.right(90)
turtle.forward(15)
turtle.end_fill()
turtle.penup()
turtle.goto(25,40)
turtle.pendown()
turtle.left(180)
turtle.color('red')

turtle.circle(25, -180)